apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-using-secret
  name: pod-using-secret
spec:
  volumes:
     - name: api-secret
       secret:
           secretName: my-secret
  containers:
  - image: nginx:1.7.9
    name: pod-using-secret
    volumeMounts:
       - name: api-secret
         mountPath: /etc/sercret
