apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-illegal
  name: pod-illegal
spec:
  containers:
  - image: nginx
    name: pod-illegal
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
