apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-illegal
  name: pod-illegal
spec:
  containers:
  - image: nginx
    name: pod-illegal
    resources:
      limits:
        cpu: "2"
        memory: 1024m
      requests:
        cpu: 500m
        memory: 768m
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
