apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secondapp
  name: secondapp
spec:
  securityContext:
        runAsUser: 1000
  containers:
  - command:
    - sleep
    - "3600"
    image: busybox
    name: secondapp
    securityContext:
        runAsUser: 2000
        allowPrivilegeEscalation: false
        capabilities:
           add:
              - NET_ADMIN
              - SYS_TIME
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
