apiVersion: v1
kind: Pod
metadata:
  name: probes-pod
spec:
  containers:
    - name: probes-pod
      image: python:2.7-alpine
      readinessProbe:
        httpGet:
          port: 8000
          path: /
        initialDelaySeconds: 5
        failureThreshold: 1
      env:
        - name: DELAY_START
          value: "45"
      command:
        - /bin/sh
      args:
        - -c
        - "echo 'sleeping...'; sleep $(DELAY_START); echo 'starting server...' ; python -m SimpleHTTPServer"
