apiVersion: v1
kind: ResourceQuota
metadata:
  name: storagequota
spec:
  hard:
     pods: 5
     "requests.cpu": 500m
     "requests.memory": 512Mi
     "limits.cpu": 700m
     "limits.memory": 1024Mi
      
