apiVersion: v1
kind: Pod
metadata:
  labels:
    run: multi-ctr-pod
  name: multi-ctr-pod
spec:
  containers:
  - image: nginx
    name: multi-ctr-pod
    ports:
    - containerPort: 80
  - image: fluent/fluentd
    name: fdlogger
