apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bash
  name: bash
spec:
  containers:
  - command: ["bash"]
    args: ["-c", "hostname > /tmp/hostname && sleep 1d"]
    image: bash
    name: bash
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
