apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-pvc
  name: pod-pvc-2
spec:
  volumes:
      - name: foo
        persistentVolumeClaim:
         claimName: mypvc
  containers:
  - command:
    - sh
    - -c
    - sleep 3600
    image: busybox
    name: pod-pvc
    volumeMounts:
         - name: foo
           mountPath: /etc/foo
