apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bb1
  name: bb1
spec:
  volumes:
     - name: foo
       emptyDir: {}
  containers:
  - command:
    - sh
    - -c
    - sleep 3600
    image: busybox
    name: bb1
    volumeMounts:
        - name: foo
          mountPath: /etc/foo
  - command:
    - sh
    - -c
    - sleep 3600
    image: busybox
    name: bb2
    volumeMounts:
        - name: foo
          mountPath: /etc/foo
