apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
    - name: task-pv-container
      image: alpine 
      volumeMounts:
        - mountPath: "/var/forever"
          name: task-pv-storage
      command: ["/bin/sh"]
      args: ["-c", "while true; do date >> /var/forever/file.txt; sleep 5; done;"]
