apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: two
  name: two
spec:
  containers:
  - image: nginx:1.7.9
    name: nginx
  - name: two
    image: busybox:1.31.0
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
