apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: emptydir-ex1
  name: emptydir-ex1
spec:
  volumes:
      - name: cache-vol
        emptyDir: {}
  containers:
  - image: cloudnatived/demo:hello
    name: emptydir-ex1
    volumeMounts:
        - name: cache-vol
          mountPath: /cache
   
