apiVersion: v1
kind: Pod
metadata:
  labels:
    run: fortune
  name: fortune
spec:
  volumes:
      - name: foo
        emptyDir: {}
  containers:
  - image: luksa/fortune
    name: fortune
    volumeMounts:
        - name: foo
          mountPath: /var/htdocs
  - image: nginx:alpine
    name: web
    volumeMounts:
        - name: foo
          mountPath: /usr/share/nginx/html
          readOnly: true
    ports:
        - containerPort: 80
