apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: redis
  name: redis
spec:
  volumes:
    - name: redis-storage
      # volume type is emptyDir whose lifetime = Pod lifetime
      emptyDir: {}
  containers:
  - image: redis
    name: redis
    volumeMounts:
     - name: redis-storage
       mountPath: /data/redis
