apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: HanuAthena
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 3
    ssh:
      publicKeyName: eks
cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator"]

availabilityZones: ["us-east-1a", "us-east-1d"]
