apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: HanuAthena
  region: us-east-1

nodeGroups:

  # MAIN
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 3
    ssh:
      publicKeyName: eks

  # SINGLE AZ FOR STATEFUL APPLNS
  - name: scale-east1a
    instanceType: t2.small
    desiredCapacity: 1
    maxSize: 3
    availabilityZones: ["us-east-1a"]
    iam:
      withAddonPolicies:
        autoScaler: true
    labels:
      nodegroup-type: stateful-east1a
      instance-type: onDemand
    ssh: # use existing EC2 key
      publicKeyName: eks

  # SINGLE AZ FOR STATEFUL APPLNS
  - name: scale-east1d
    instanceType: t2.small
    desiredCapacity: 1
    maxSize: 3
    availabilityZones: ["us-east-1d"]
    iam:
      withAddonPolicies:
        autoScaler: true
    labels:
      nodegroup-type: stateful-east1d
      instance-type: onDemand
    ssh: # use existing EC2 key
      publicKeyName: eks

   # AUTOSCALE SPOT INSTANCES
  - name: scale-spot
    desiredCapacity: 1
    maxSize: 3
    instancesDistribution:
      instanceTypes: ["t2.small", "t3.small"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
    availabilityZones: ["us-east-1a", "us-east-1d"]
    iam:
      withAddonPolicies:
        autoScaler: true
    labels:
      nodegroup-type: stateless-workload
      instance-type: spot
    ssh:
      publicKeyName: eks

availabilityZones: ["us-east-1a", "us-east-1d"]
