apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  labels:
     vol: mysql-db-vol
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
       path: /home/jai/db-pv-hostpathdata
