apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  volumes:
     - name: svol
       secret:
        secretName: mysecret2
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
          - name: svol
            mountPath: /etc/foo
    env:
      - name: USERNAME
        valueFrom:
            secretKeyRef:
                name: mysecret2
                key: username
