apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: liveness
    image: nginx 
    ports:
        - containerPort: 80
    livenessProbe:
      exec:
        command:
        - ls 
      initialDelaySeconds: 5
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: /
        port: 80
