apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: mypvc 
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      command: 
          - sh
          - -c
          - sleep 3600
      volumeMounts:
        - mountPath: "/etc/foo"
          name: task-pv-storage

