apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bb
  name: bb
spec:
  containers:
  - args:
    - sleep
    - "3600"
    image: buxybox
    name: bb
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
