apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bb
  name: bb
spec:
  volumes:
    - name: avol
      emptyDir: {}
  containers:
  - image: busybox
    name: bb
    volumeMounts:
       - name: avol
         mountPath: /tmp
  - image: busybox
    name: bb2
    volumeMounts:
       - name: avol
         mountPath: /docs
